defaults: &defaults
  download:
    path: "#{Rails.root}/tmp/donwload"
  books:
    width: 300
  basic:
    username: 'username'
    password: 'password'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
